# pylint: disable=missing-module-docstring
from __future__ import annotations

import argparse
import importlib
import inspect
import os
import sys
from pathlib import Path
from typing import get_overloads

import black
import isort
from bec_lib.logger import bec_logger
from qtpy.QtCore import Property as QtProperty

from bec_widgets.utils.generate_designer_plugin import (
    DesignerPluginGenerator,
    DesignerPluginInfo,
    plugin_filenames,
)
from bec_widgets.utils.plugin_utils import BECClassContainer, get_custom_classes

logger = bec_logger.logger


class ClientGenerator:
    def __init__(self, base=False):
        self._base = base
        base_imports = (
            """import enum
import inspect
import traceback
from functools import reduce
from operator import add
from typing import Literal, Optional
"""
            if self._base
            else "\n"
        )
        self.header = f"""# This file was automatically generated by generate_cli.py
# type: ignore \n
from __future__ import annotations
{base_imports}
from bec_lib.logger import bec_logger

from bec_widgets.cli.rpc.rpc_base import RPCBase, rpc_call, rpc_timeout
{"from bec_widgets.utils.bec_plugin_helper import get_plugin_client_module" if self._base else ""}

logger = bec_logger.logger

# pylint: skip-file"""

        self.content = ""

    def generate_client(self, class_container: BECClassContainer):
        """
        Generate the client for the published classes, skipping any classes
        that have `RPC = False`.

        Args:
            class_container: The class container with the classes to generate the client for.
        """
        # Filter out classes that explicitly have RPC=False
        rpc_top_level_classes = [
            cls for cls in class_container.rpc_top_level_classes if getattr(cls, "RPC", True)
        ]
        rpc_top_level_classes.sort(key=lambda x: x.__name__)

        connector_classes = [
            cls for cls in class_container.connector_classes if getattr(cls, "RPC", True)
        ]
        connector_classes.sort(key=lambda x: x.__name__)

        self.write_client_enum(rpc_top_level_classes)
        for cls in connector_classes:
            logger.debug(f"generating RPC client class for {cls.__name__}")
            self.content += "\n\n"
            self.generate_content_for_class(cls)

    def write_client_enum(self, published_classes: list[type]):
        """
        Write the client enum to the content.
        """
        if self._base:
            self.content += """
class _WidgetsEnumType(str, enum.Enum):
    \"\"\" Enum for the available widgets, to be generated programmatically  \"\"\"
    ...
    """

        self.content += """

_Widgets = {
    """
        for cls in published_classes:
            self.content += f'"{cls.__name__}": "{cls.__name__}",\n    '

        self.content += """}
"""
        if self._base:
            self.content += """

try:
    plugin_client = get_plugin_client_module()
    for plugin_name, plugin_class in inspect.getmembers(plugin_client, inspect.isclass):
        if issubclass(plugin_class, RPCBase) and plugin_class is not RPCBase:
            if plugin_name not in _Widgets:
                _Widgets[plugin_name] = plugin_name
            if plugin_name in globals():
                logger.warning(
                    f"Plugin widget {plugin_name} in {plugin_class._IMPORT_MODULE} conflicts with a built-in class!"
                )
                continue
            else:
                globals()[plugin_name] = plugin_class
        Widgets = _WidgetsEnumType("Widgets", _Widgets)
except ImportError as e:
    logger.error(f"Failed loading plugins: \\n{reduce(add, traceback.format_exception(e))}")
"""

    def generate_content_for_class(self, cls):
        """
        Generate the content for the class.

        Args:
            cls: The class for which to generate the content.
        """

        class_name = cls.__name__

        self.content += f"""
class {class_name}(RPCBase):\n"""

        if cls.__doc__:
            # We only want the first line of the docstring
            # But skip the first line if it's a blank line
            first_line = cls.__doc__.split("\n")[0]
            if first_line:
                class_docs = first_line
            else:
                class_docs = cls.__doc__.split("\n")[1]
            self.content += f"""
    \"\"\"{class_docs}\"\"\"\n"""
        user_access_entries = self._get_user_access_entries(cls)
        self.content += f'    _IMPORT_MODULE="{cls.__module__}"\n'
        for method_entry in user_access_entries:
            method, obj, is_property_setter = self._resolve_method_object(cls, method_entry)
            if obj is None:
                raise AttributeError(
                    f"Method {method} not found in class {cls.__name__}. "
                    f"Please check the USER_ACCESS list."
                )
            if hasattr(obj, "__rpc_timeout__"):
                timeout = {"value": obj.__rpc_timeout__}
            else:
                timeout = {}
            if isinstance(obj, (property, QtProperty)):
                # for the cli, we can map qt properties to regular properties
                if is_property_setter:
                    self.content += f"""
    @{method}.setter
    @rpc_call"""
                else:
                    self.content += """
    @property
    @rpc_call"""

                sig = str(inspect.signature(obj.fget))
                doc = inspect.getdoc(obj.fget)
            else:
                sig = str(inspect.signature(obj))
                doc = inspect.getdoc(obj)
                overloads = get_overloads(obj)
                for overload in overloads:
                    sig_overload = str(inspect.signature(overload))
                    self.content += f"""
    @overload
    def {method}{str(sig_overload)}: ...
    """

                self.content += f"""
    {self._rpc_call(timeout)}"""
            self.content += f"""
    def {method}{str(sig)}:
        \"\"\"
{doc}
        \"\"\""""

    @staticmethod
    def _get_user_access_entries(cls) -> list[str]:
        entries = list(getattr(cls, "USER_ACCESS", []))
        content_cls = getattr(cls, "RPC_CONTENT_CLASS", None)
        if content_cls is not None:
            entries.extend(getattr(content_cls, "USER_ACCESS", []))
        return list(dict.fromkeys(entries))

    @staticmethod
    def _resolve_method_object(cls, method_entry: str):
        method_name = method_entry
        is_property_setter = False

        if method_entry.endswith(".setter"):
            is_property_setter = True
            method_name = method_entry.split(".setter")[0]

        candidate_classes = [cls]
        content_cls = getattr(cls, "RPC_CONTENT_CLASS", None)
        if content_cls is not None:
            candidate_classes.append(content_cls)

        for candidate_cls in candidate_classes:
            obj = getattr(candidate_cls, method_name, None)
            if obj is not None:
                return method_name, obj, is_property_setter
        return method_name, None, is_property_setter

    def _rpc_call(self, timeout_info: dict[str, float | None]):
        """
        Decorator to mark a method as an RPC call.
        This is used to generate the client code for the method.
        """
        if not timeout_info:
            return "@rpc_call"
        timeout = timeout_info.get("value", None)
        return f"""
    @rpc_timeout({timeout})
    @rpc_call"""

    def write(self, file_name: str):
        """
        Write the content to a file, automatically formatted with black.

        Args:
            file_name(str): The name of the file to write to.
        """
        # Combine header and content, then format with black
        full_content = self.header + "\n" + self.content
        try:
            formatted_content = black.format_str(full_content, mode=black.Mode(line_length=100))
        except black.NothingChanged:
            formatted_content = full_content

        config = isort.Config(
            profile="black",
            line_length=100,
            multi_line_output=3,
            include_trailing_comma=False,
            known_first_party=["bec_widgets"],
        )
        formatted_content = isort.code(formatted_content, config=config)

        with open(file_name, "w", encoding="utf-8") as file:
            file.write(formatted_content)


def write_designer_plugins(plugin_infos: list[DesignerPluginInfo], file_name: str):
    """
    Write a registry of Qt widget classes with designer plugins.

    Args:
        plugin_infos(list[DesignerPluginInfo]): The designer plugin metadata to write.
        file_name(str): The name of the file to write to.
    """
    plugin_infos = sorted(plugin_infos, key=lambda info: info.plugin_name_pascal)
    content = """# This file was automatically generated by generate_cli.py
# type: ignore
from __future__ import annotations

# pylint: skip-file

designer_plugins = {
"""
    for info in plugin_infos:
        widget_module = info.plugin_class.__module__
        widget_class = info.plugin_name_pascal
        content += f'    "{info.plugin_name_pascal}": ("{widget_module}", "{widget_class}"),\n'

    content += """
}

widget_icons = {
"""
    for info in plugin_infos:
        content += f'    "{info.plugin_name_pascal}": "{info.icon_name}",\n'

    content += """
}
"""

    try:
        formatted_content = black.format_str(content, mode=black.Mode(line_length=100))
    except black.NothingChanged:
        formatted_content = content

    config = isort.Config(
        profile="black",
        line_length=100,
        multi_line_output=3,
        include_trailing_comma=False,
        known_first_party=["bec_widgets"],
    )
    formatted_content = isort.code(formatted_content, config=config)

    with open(file_name, "w", encoding="utf-8") as file:
        file.write(formatted_content)


def main():
    """
    Main entry point for the script, controlled by command line arguments.
    """

    parser = argparse.ArgumentParser(description="Auto-generate the client for RPC widgets")
    parser.add_argument(
        "--target",
        action="store",
        type=str,
        help="Which package to generate plugin files for. Should be installed in the local environment (example: my_plugin_repo)",
    )

    args = parser.parse_args()
    if args.target is None:
        logger.error(
            "You must provide a target - for safety, the default of running this on bec_widgets core has been removed. To generate the client for bec_widgets, run `bw-generate-cli --target bec_widgets`"
        )
        return

    logger.info(f"BEC Widget code generation tool started with args: {args}")

    client_subdir = "cli" if args.target == "bec_widgets" else "widgets"
    module_name = "bec_widgets" if args.target == "bec_widgets" else f"{args.target}.bec_widgets"

    try:
        module = importlib.import_module(module_name)
        assert module.__file__ is not None
        module_file = Path(module.__file__)
        module_dir = module_file.parent if module_file.is_file() else module_file
    except Exception as e:
        logger.error(f"Failed to load module {module_name} for code generation: {e}")
        return

    client_path = module_dir / client_subdir / "client.py"

    packages = ("widgets", "applications") if module_name == "bec_widgets" else ("widgets",)
    rpc_classes = get_custom_classes(module_name, packages=packages)
    logger.info(f"Obtained classes with RPC objects: {rpc_classes!r}")

    generator = ClientGenerator(base=module_name == "bec_widgets")
    logger.info(f"Generating client file at {client_path}")
    generator.generate_client(rpc_classes)
    generator.write(str(client_path))

    if module_name != "bec_widgets":
        non_overwrite_classes = list(clsinfo.name for clsinfo in get_custom_classes("bec_widgets"))
        logger.info(
            f"Not writing plugins which would conflict with builtin classes: {non_overwrite_classes}"
        )
    else:
        non_overwrite_classes = []

    designer_plugin_infos = []

    for cls in rpc_classes.plugins:
        logger.info(f"Writing bec-designer plugin files for {cls.__name__}...")

        if cls.__name__ in non_overwrite_classes:
            logger.error(
                f"Not writing plugin files for {cls.__name__} because a built-in widget with that name exists"
            )
            continue

        plugin = DesignerPluginGenerator(cls)
        if not hasattr(plugin, "info") or plugin.excluded:
            continue

        def _exists(file: str):
            return os.path.exists(os.path.join(plugin.info.base_path, file))

        if any(_exists(file) for file in plugin_filenames(plugin.info.plugin_name_snake)):
            if _exists(plugin.filenames.plugin):
                designer_plugin_infos.append(plugin.info)
            logger.debug(
                f"Skipping generation of extra plugin files for {plugin.info.plugin_name_snake} - at least one file out of 'plugin.py', 'pyproject', and 'register_{plugin.info.plugin_name_snake}.py' already exists."
            )
            continue

        plugin.run()
        designer_plugin_infos.append(plugin.info)

    # Write designer_plugins.py with plugin import metadata for all widgets with designer plugins.
    designer_plugins_path = module_dir / client_subdir / "designer_plugins.py"
    logger.info(f"Generating designer plugin registry at {designer_plugins_path}")
    write_designer_plugins(designer_plugin_infos, str(designer_plugins_path))


if __name__ == "__main__":  # pragma: no cover
    import sys

    sys.argv = ["bw-generate-cli", "--target", "bec_widgets"]
    main()
