name: Full CI
on: [push, pull_request]

permissions:
  pull-requests: write

jobs:
  formatter:
    uses: ./.github/workflows/formatter.yml

  unit-test:
    uses: ./.github/workflows/pytest.yml
    with:
        pr_number: ${{ github.event.pull_request.number }}

  unit-test-matrix:
    uses: ./.github/workflows/pytest-matrix.yml

  end2end-test:
    uses: ./.github/workflows/end2end-conda.yml