name: Run Pytest with Coverage
on: 
  workflow_call:
      inputs:
        pr_number:
          description: 'Pull request number'
          required: false
          type: number


permissions:
  pull-requests: write

jobs:
  pytest:
    runs-on: ubuntu-latest

    env:
      CHILD_PIPELINE_BRANCH: main  # Set the branch you want for ophyd_devices
      BEC_CORE_BRANCH: main        # Set the branch you want for bec
      OPHYD_DEVICES_BRANCH: main   # Set the branch you want for ophyd_devices
      PROJECT_PATH: ${{ github.repository }}
      QTWEBENGINE_DISABLE_SANDBOX: 1
      QT_QPA_PLATFORM: "offscreen"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libegl1 x11-utils libxkbcommon-x11-0 libdbus-1-3 xvfb
          sudo apt-get -y install libnss3 libxdamage1 libasound2t64 libatomic1 libxcursor1

      - name: Clone and install dependencies
        run: |
          echo -e "\033[35;1m Using branch $BEC_CORE_BRANCH of BEC CORE \033[0;m";
          git clone --branch $BEC_CORE_BRANCH https://gitlab.psi.ch/bec/bec.git
          echo -e "\033[35;1m Using branch $OPHYD_DEVICES_BRANCH of OPHYD_DEVICES \033[0;m";
          git clone --branch $OPHYD_DEVICES_BRANCH https://gitlab.psi.ch/bec/ophyd_devices.git
          export OHPYD_DEVICES_PATH=$PWD/ophyd_devices
          pip install -e ./ophyd_devices
          pip install -e ./bec/bec_lib[dev]
          pip install -e ./bec/bec_ipython_client
          pip install -e .[dev,pyside6]

      - name: Run Pytest with Coverage
        id: coverage
        run: |
          pip install coverage pytest pytest-random-order
          coverage run --source=./bec_widgets -m pytest -v --junitxml=report.xml --maxfail=2 --random-order --full-trace ./tests/unit_tests

          full_report=$(coverage report)
          coverage xml -i -o coverage.cobertura.xml

            # Extract total coverage %
          COVERAGE=$(echo "$full_report" | grep TOTAL | awk '{print $4}' | sed 's/%//')
          echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.cobertura.xml
          format: 'markdown'
          output: 'both'

      - name: Format Coverage Report
        shell: bash
        run: |
          tmpfile=$(cat code-coverage-results.md)
          echo "## Code Coverage Report" > code-coverage-results-formatted.md
          echo "![Coverage Badge](https://img.shields.io/badge/coverage-${{ steps.coverage.outputs.coverage }}%25-brightgreen)" >> code-coverage-results-formatted.md
          echo "<details>" >> code-coverage-results-formatted.md
          echo "<summary>Code Coverage</summary>" >> code-coverage-results-formatted.md
          echo >> code-coverage-results-formatted.md
          echo >> code-coverage-results-formatted.md
          echo "$tmpfile" >> code-coverage-results-formatted.md
          echo "</details>" >> code-coverage-results-formatted.md

      - name: Add Coverage PR Comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ github.event.pull_request.number }}
          recreate: true
          path: code-coverage-results-formatted.md

      - name: Write Coverage to Job Summary
        shell: bash
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY